print("LIST Operations \n")
mylist=[1024, 3, True, 6.5]
mylist.append(False)
print(mylist)
mylist.insert(2,4.5)
print(mylist)
print(mylist.pop())
print(mylist)
print(mylist.pop(1))
print(mylist)
mylist.pop(2)
print(mylist)
mylist.sort()
print(mylist)
mylist.reverse()
print(mylist)
print(mylist.count(6.5))
print(mylist.index(4.5))
mylist.remove(6.5)
print(mylist)
del mylist[0]
print(mylist)
print("LIST+range Operations \n")
print(range(10))
print(list(range(10)))
print(range(5,10))
print(list(range(5,10,2)))
print(list(range(10,1,-1)))
print("String operations \n")
print("Strings are immutable while lists are mutable \n")
myname="David"
print(myname[3])
print(len(myname))
print(myname.upper())
print(myname.center(10))
print(myname.find('v'))
print(myname.split('v'))
print ("TUPLE same as list but immutable")
mytuple=(2,True,4.9)
print(mytuple)
print(len(mytuple))
print ("Set is unordered, no duplicates\n")
myset={1,4.5,True,"cat"}
print(myset)
newset={1, 6, False, True}
print(newset)
print(myset|newset)
print(myset&newset)
print(myset-newset)
print(myset.union(newset))
print(myset.intersection(newset))
print(myset.difference(newset))
print({"cat",True}.issubset(myset))
print(myset.add("house"))
print(myset)
print(myset.pop())
print(myset)
print(myset.clear())
print("DICTIONARY is unordered\n")
phone={'david':1410,'brad':1132}
print(phone)
print(phone.keys())
print(list(phone.keys()))
print(list(phone.values()))
print(list(phone.items()))
print(phone['david'])
print(phone.get('david'))
print(phone.get('dummy',"NOT THERE"))
for k in phone:
	print (phone[k], "is the phone number of ", k)

